---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-cfcli
    tag: "latest"

inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/create-space.sh

params:
  CF_API:
  CF_USER:
  CF_PASS:
  CF_ORG:
  CF_SPACE: