---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-cfcli
    tag: "latest"

inputs:
  - name: git-repo
  - name: version
  - name: release-candidate

run:
  path: git-repo/ci/tasks/deploy-artifact.sh

params:
  CF_API:
  CF_USER:
  CF_PASS:
  CF_ORG:
  CF_SPACE:
  CF_APP:
  ARTIFACT_PATH:
  CF_ROUTE:
