jobs:
- name: build-jar
  serial_groups: [version]
  plan:
  - get: git-repo
    trigger: true
  - get: version
    params: {bump: minor}
  - task: build-artifact
    file: git-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: release-candidate
    params:
      file: artifact-dir/IoTConnectedCarEmulator-*.jar
  - put: git-repo
    params:
      repository: git-repo
      tag: version/number
  - put: version
    params: {file: version/number}

- name: deploySpace1
  serial_groups: [version]
  plan:
    - aggregate:
      - get: release-candidate
        passed: [build-jar]
        trigger: true
      - get: git-repo
        passed: [build-jar]
      - get: version
        passed: [build-jar]
    - task: create-space
      file: git-repo/ci/tasks/create-space.yml
      params:
        CF_API: {{CF_API}}
        CF_USER: {{CF_USER_1}}
        CF_PASS: {{CF_PASS}}
        CF_ORG: {{CF_ORG_1}}
        CF_SPACE: {{CF_SPACE}}
    - task: deploy
      file: git-repo/ci/tasks/deploy-artifact.yml
      params:
        CF_API: {{CF_API}}
        CF_USER: {{CF_USER_1}}
        CF_PASS: {{CF_PASS}}
        CF_ORG: {{CF_ORG_1}}
        CF_SPACE: {{CF_SPACE}}
        ARTIFACT_PATH: release-candidate/IoTConnectedCarEmulator-*.jar
        CF_ROUTE: {{CF_APP_1}}


resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: release-candidate
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: connectedCar/pipeline-artifacts/IoTConnectedCarEmulator-(.*).jar
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: connectedCar/pipeline-artifacts/current-version
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0
