jobs:
- name: build-jar
  plan:
  - get: git-repo
  - get: version
    params: {bump: minor}
  - task: build-artifact
    file: git-repo/ci/tasks/build-artifact.yml
    timeout: 5m
  - put: release-candidate
    params:
      file: artifact-dir/IoTConnectedCarEmulator-*.jar
  - put: git-repo
    params:
      repository: git-repo
      tag: version/number
  - put: version
    params: {file: version/number}

- name: deployAllTheThings
  plan:
    - get: git-repo
      trigger: true
      passed: [build-jar]
    - put: deploy-app-space-1
      params:
      current_app_name: {{APP_1}}
      path: release-candidate/IoTConnectedCarEmulator-*.jar


resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-app-space-1
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER_1}}
    password: {{CF_PASS}}
    organization: {{CF_ORG_1}}
    space: {{CF_SPACE}}

- name: release-candidate
  type: s3
  source:
    bucket: {{S3_BUCKET}}
    regexp: connectedCar/pipeline-artifacts/IoTConnectedCarEmulator-(.*).jar
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}

- name: version
  type: semver
  source:
    bucket: {{S3_BUCKET}}
    key: connectedCar/pipeline-artifacts/current-version
    access_key_id: {{S3_ACCESS_KEY_ID}}
    secret_access_key: {{S3_SECRET_ACCESS_KEY}}
    initial_version: 1.0.0
